### PR TITLE
Snippet that creates a recurring event

### PR DESCRIPTION
**Pull request by davidchesnut**
Added a new snippet that will create a calendar event that occurs every Tuesday and Thursday from 1PM to 2PM.

### CODE REVIEW

**Comment by iambmelt** [comment]
@davechmsft I'd be happy to take a look at this. Sound good, @Ricalo?

**Comment by ricalo** [comment]
Please do...

**Comment by iambmelt** [comment]
Passing back to @davechmsft to check my amends

**Comment by davidchesnut** [comment]
@iambmelt the formatting changes look good.

**Pull request merged**
